//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Web;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ProjektBeer.DB
{

    public partial class Beer
    {
        public int IdBeer { get; set; }
        
        [Required]
        [StringLength(30)]
        public string Title { get; set; }

        [Required]
        [StringLength(30)]
        public string Style { get; set; }

        [Required]
        [StringLength(500)]
        public string BeerDes { get; set; }

        [Required]
        [Range(1,100)]
        public Nullable<int> Price { get; set; }

        [DisplayName("IUpload FIle")]
        public string ImagePath { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
